'use strict'
var mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');
var Schema = mongoose.Schema;


var   prelinguisticas = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number,
  actividad26: Number,
  actividad27: Number,
  actividad28: Number,
  actividad29: Number,
  actividad30: Number
  
} ,{ _id : false });
var   prearticulatorias = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number,
  actividad26: Number
  
},{ _id : false });
var   psicolinguisticas = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number
  
},{ _id : false });
var   foneticoFonologico = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number,
  actividad26: Number,
  actividad27: Number,
  actividad28: Number,
  actividad29: Number,
  actividad30: Number,
  actividad31: Number,
  actividad32: Number,
  actividad33: Number,
  actividad34: Number,
  actividad35: Number,
  actividad36: Number,
  actividad37: Number,
  actividad38: Number,
  actividad39: Number,
  actividad40: Number,
  actividad41: Number,
  actividad42: Number,
  actividad43: Number,
  actividad44: Number,
  actividad45: Number,
  actividad46: Number,
  actividad47: Number,
  actividad48: Number,
  actividad49: Number,
  actividad50: Number,
  actividad51: Number,
  actividad52: Number,
  actividad53: Number,
  actividad54: Number,
  actividad55: Number,
  actividad56: Number,
  actividad57: Number,
  actividad58: Number,
  actividad59: Number,
  actividad60: Number,
  actividad61: Number,
  actividad62: Number,
  actividad63: Number,
  actividad64: Number,
  actividad65: Number,
  actividad66: Number,
  actividad67: Number,
  actividad68: Number,
  actividad69: Number,
  actividad70: Number,
  actividad71: Number,
  actividad72: Number,
  actividad73: Number,
  actividad74: Number
  
},{ _id : false });
var   semantico = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number,
  actividad26: Number,
  actividad27: Number,
  actividad28: Number
  
},{ _id : false });
var   morfosintactico = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number
  
},{ _id : false });
var   pragmatico = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number,
  actividad9: Number,
  actividad10: Number,
  actividad11: Number,
  actividad12: Number,
  actividad13: Number,
  actividad14: Number,
  actividad15: Number,
  actividad16: Number,
  actividad17: Number,
  actividad18: Number,
  actividad19: Number,
  actividad20: Number,
  actividad21: Number,
  actividad22: Number,
  actividad23: Number,
  actividad24: Number,
  actividad25: Number,
  actividad26: Number,
  actividad27: Number,
  actividad28: Number
  
},{ _id : false });
var   discursoNarrativo = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number,
  actividad8: Number
  
},{ _id : false });
var  socialComunicativa = new Schema({
  actividad1: Number,
  actividad2: Number,
  actividad3: Number,
  actividad4: Number,
  actividad5: Number,
  actividad6: Number,
  actividad7: Number
  
},{ _id : false });
var FonoaudiologiaSchema = new Schema({

	paciente: { type: Schema.Types.ObjectId,ref:'Paciente',required: [true,'El paciente es necesario']},
	user: { type: Schema.Types.ObjectId,ref:'User',unique: false ,required: [true,'El profesional es necesario']},
	fecha: { type: String, required: [true,'La fecha es necesario']},
	prelinguisticas: prelinguisticas,
	prearticulatorias: prearticulatorias,
	psicolinguisticas: psicolinguisticas,
	foneticoFonologico: foneticoFonologico,
	semantico: semantico,
	morfosintactico: morfosintactico,
	pragmatico: pragmatico,
	discursoNarrativo: discursoNarrativo,
	socialComunicativa: socialComunicativa

	
},{ collection: 'fonoaudiologia'}); // esto es para evitar que se grave como 

//UserSchema.plugin( uniqueValidator, { message: '{PATH} debe ser único'}) //afecta a los campos con unique: true. PATH toma el valor del campo correspondiente

module.exports = mongoose.model('Fonoaudiologia', FonoaudiologiaSchema);