'use strict'
var mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');
var Schema = mongoose.Schema;


var  estabilidadDesplazamiento = new Schema({
	 objetivoEsp1: Number,
	 objetivoEsp2: Number,
	 objetivoEsp3: Number,
	 objetivoEsp4: Number,
	 objetivoEsp5: Number,
	 objetivoEsp6: Number,
	 objetivoEsp7: Number,
	 objetivoEsp8: Number,
	 objetivoEsp9: Number,
	 objetivoEsp10: Number,
	 objetivoEsp11: Number,
	 objetivoEsp12: Number,
	 objetivoEsp13: Number,
	 objetivoEsp14: Number,
	 objetivoEsp15: Number,
	 objetivoEsp16: Number,
	 objetivoEsp17: Number,
	 objetivoEsp18: Number,
	 objetivoEsp19: Number,
	 objetivoEsp20: Number,
	 objetivoEsp21: Number,
	 objetivoEsp22: Number,
	 objetivoEsp23: Number,
	 objetivoEsp24: Number,
	 objetivoEsp25: Number,
	 objetivoEsp26: Number,
	 objetivoEsp27: Number,
	 objetivoEsp28: Number,
	 objetivoEsp29: Number,
	 objetivoEsp30: Number,
	 objetivoEsp31: Number,
	 objetivoEsp32: Number,
	 objetivoEsp33: Number,
	 objetivoEsp34: Number,
	 objetivoEsp35: Number,
	 objetivoEsp36: Number,
	 objetivoEsp37: Number,
},{ _id : false });

var  coordinacionDinamica = new Schema({
	 objetivoEsp1: Number,
	 objetivoEsp2: Number,
	 objetivoEsp3: Number,
	 objetivoEsp4: Number,
	 objetivoEsp5: Number,
	 objetivoEsp6: Number,
	 objetivoEsp7: Number,
	 objetivoEsp8: Number,
	 objetivoEsp9: Number,
	 objetivoEsp10: Number,
	 objetivoEsp11: Number,
	 objetivoEsp12: Number,
	 objetivoEsp13: Number,
	 objetivoEsp14: Number,
	 objetivoEsp15: Number,
	 objetivoEsp16: Number,
	 objetivoEsp17: Number,
	 objetivoEsp18: Number,
	 objetivoEsp19: Number,
	 objetivoEsp20: Number,
	 objetivoEsp21: Number,
	 objetivoEsp22: Number,
	 objetivoEsp23: Number,
	 objetivoEsp24: Number,
	 objetivoEsp25: Number,
	 objetivoEsp26: Number,
	 objetivoEsp27: Number,
	 objetivoEsp28: Number
},{ _id : false });

var  conductasPsicomotoras = new Schema({
	 objetivoEsp1: Number,
	 objetivoEsp2: Number,
	 objetivoEsp3: Number,
	 objetivoEsp4: Number,
	 objetivoEsp5: Number,
	 objetivoEsp6: Number,
	 objetivoEsp7: Number,
	 objetivoEsp8: Number,
	 objetivoEsp9: Number,
	 objetivoEsp10: Number,
	 objetivoEsp11: Number,
	 objetivoEsp12: Number,
	 objetivoEsp13: Number,
	 objetivoEsp14: Number,
	 objetivoEsp15: Number,
	 objetivoEsp16: Number,
	 objetivoEsp17: Number,
	 objetivoEsp18: Number,
	 objetivoEsp19: Number,
	 objetivoEsp20: Number,
	 objetivoEsp21: Number,
	 objetivoEsp22: Number,
	 objetivoEsp23: Number,
	 objetivoEsp24: Number,
	 objetivoEsp25: Number,
	 objetivoEsp26: Number,
	 objetivoEsp27: Number,
	 objetivoEsp28: Number,
	 objetivoEsp29: Number,
	 objetivoEsp30: Number,
	 objetivoEsp31: Number,
	 objetivoEsp32: Number,
	 objetivoEsp33: Number,
	 objetivoEsp34: Number,
	 objetivoEsp35: Number,
	 objetivoEsp36: Number,
	 objetivoEsp37: Number,
	 objetivoEsp38: Number,
	 objetivoEsp39: Number
	
},{ _id : false });
var  alineacionPostural = new Schema({
	 objetivoEsp1: Number,
	 objetivoEsp2: Number,
	 objetivoEsp3: Number,
	 objetivoEsp4: Number,
	 objetivoEsp5: Number,
	 objetivoEsp6: Number,
	 objetivoEsp7: Number,
	 objetivoEsp8: Number,
	 objetivoEsp9: Number,
	 objetivoEsp10: Number,
	 objetivoEsp11: Number,
	 objetivoEsp12: Number,
	 objetivoEsp13: Number,
	 objetivoEsp14: Number,
	 objetivoEsp15: Number,
	 objetivoEsp16: Number,
	 objetivoEsp17: Number,
	 objetivoEsp18: Number,
	 objetivoEsp19: Number,
	 objetivoEsp20: Number,
	 objetivoEsp21: Number,
	 objetivoEsp22: Number,
	 objetivoEsp23: Number,
	 objetivoEsp24: Number,
	 objetivoEsp25: Number,
	 objetivoEsp26: Number,
	 objetivoEsp27: Number,
	 objetivoEsp28: Number,
	 objetivoEsp29: Number,
	 objetivoEsp30: Number,
	 objetivoEsp31: Number,
	 objetivoEsp32: Number,
	 objetivoEsp33: Number,
	 objetivoEsp34: Number,
	 objetivoEsp35: Number
	
},{ _id : false });

var KinesiologiaSchema = new Schema({

	paciente: { type: Schema.Types.ObjectId,ref:'Paciente',required: [true,'El paciente es necesario']},
	user: { type: Schema.Types.ObjectId,ref:'User',unique: false ,required: [true,'El profesional es necesario']},
	fecha: { type: String, required: [true,'La fecha es necesario']},
	estabilidadDesplazamiento :estabilidadDesplazamiento,
	coordinacionDinamica: coordinacionDinamica,
	conductasPsicomotoras: conductasPsicomotoras,
	alineacionPostural: alineacionPostural
	
},{ collection: 'kinesiologia'}); // esto es para evitar que se grave como 

//UserSchema.plugin( uniqueValidator, { message: '{PATH} debe ser único'}) //afecta a los campos con unique: true. PATH toma el valor del campo correspondiente

module.exports = mongoose.model('Kinesiologia', KinesiologiaSchema);